pubtator:
  base_url: "https://ftp.ncbi.nlm.nih.gov/pub/lu/PubTator3/"
  files:
    - "disease2pubtator3.gz"
    - "chemical2pubtator3.gz"
    - "gene2pubtator3.gz"
    - "relation2pubtator3.gz"
  temp_dir: "./data/raw/pubtator/temp"

database:
  pubtator_db: "./data/processed/pubtator.db"
  
download:
  chunk_size: 8192

ncbi:
  gene_info_file: "Homo_sapiens.gene_info.gz"
  gene_info_url: "https://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/"
  table_name: "homo_sapiens_genes"
  temp_dir: "./data/raw/ncbi/temp"

database:
  ncbi_db: "./data/processed/ncbi.db"

nodes:
  table_name: "nodes"